image: gitpod/workspace-postgres

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - init: >
    command: rails server -b 0.0.0.0
